baseURL = "https://lynette-adams.netlify.app/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Home Valuation"
parent = "Sellers"
url = "/home-valuation"
weight = 1
[[menu.main]]
name = "Sellers"
weight = 4
[[menu.main]]
name = "Search Homes"
parent = "Buyers"
weight = 1
[[menu.main]]
name = "Buyers"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
